"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.registerSettings = registerSettings;
const settings_1 = require("@rocket.chat/apps-engine/definition/settings");
async function registerSettings(configuration) {
    await Promise.all([
        configuration.settings.provideSetting({
            id: 'backend-url',
            type: settings_1.SettingType.STRING,
            required: true,
            public: false,
            i18nLabel: 'Backend URL',
            i18nDescription: 'URL of the Node.js RAG backend service (e.g. http://backend:8000)',
            i18nPlaceholder: 'http://backend:8000',
            packageValue: 'http://backend:8000',
        }),
        configuration.settings.provideSetting({
            id: 'integration-token',
            type: settings_1.SettingType.PASSWORD,
            required: false,
            public: false,
            i18nLabel: 'Integration Token',
            i18nDescription: 'Shared secret token for authenticating requests with the Node backend',
            packageValue: '',
        }),
        configuration.settings.provideSetting({
            id: 'api-key',
            type: settings_1.SettingType.PASSWORD,
            required: false,
            public: false,
            i18nLabel: 'Legacy API Key',
            i18nDescription: 'Legacy API key fallback for authenticating with the backend',
            packageValue: '',
        }),
        configuration.settings.provideSetting({
            id: 'workspace-id',
            type: settings_1.SettingType.STRING,
            required: false,
            public: false,
            i18nLabel: 'Workspace Identifier',
            i18nDescription: 'Identifier for this Rocket.Chat instance (defaults to "default")',
            packageValue: 'default',
        }),
        configuration.settings.provideSetting({
            id: 'model',
            type: settings_1.SettingType.SELECT,
            required: true,
            public: false,
            i18nLabel: 'LLM Model',
            i18nDescription: 'Language model for answer generation',
            packageValue: 'openai/gpt-4o-mini',
            values: [
                { key: 'openai/gpt-4o-mini', i18nLabel: 'GPT-4o Mini' },
                { key: 'openai/gpt-4o', i18nLabel: 'GPT-4o' },
                { key: 'anthropic/claude-3-5-sonnet', i18nLabel: 'Claude 3.5 Sonnet' },
                { key: 'google/gemini-2.0-flash-001', i18nLabel: 'Gemini 2.0 Flash' },
            ],
        }),
        configuration.settings.provideSetting({
            id: 'embedding-model',
            type: settings_1.SettingType.SELECT,
            required: true,
            public: false,
            i18nLabel: 'Embedding Model',
            i18nDescription: 'Model for generating document and query embeddings',
            packageValue: 'openai/text-embedding-3-small',
            values: [
                { key: 'openai/text-embedding-3-small', i18nLabel: 'OpenAI text-embedding-3-small' },
                { key: 'openai/text-embedding-3-large', i18nLabel: 'OpenAI text-embedding-3-large' },
            ],
        }),
        configuration.settings.provideSetting({
            id: 'max-history',
            type: settings_1.SettingType.NUMBER,
            required: false,
            public: true,
            i18nLabel: 'Max Conversation History',
            i18nDescription: 'Maximum number of messages to keep in conversation history',
            packageValue: 10,
        }),
        configuration.settings.provideSetting({
            id: 'temperature',
            type: settings_1.SettingType.NUMBER,
            required: false,
            public: true,
            i18nLabel: 'LLM Temperature',
            i18nDescription: 'Controls randomness in responses (0.0 = deterministic, 1.0 = creative)',
            packageValue: 0.7,
        }),
        configuration.settings.provideSetting({
            id: 'enable-citations',
            type: settings_1.SettingType.BOOLEAN,
            required: false,
            public: true,
            i18nLabel: 'Enable Citations',
            i18nDescription: 'Show document sources with each answer',
            packageValue: true,
        }),
    ]);
}
